{% set name = "mnemonic" %}
{% set version = "0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mnemonic-{{ version }}.tar.gz
  sha256: 1fe496356820984f45559b1540c80ff10de448368929b9c60a2b55744cc88acf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.6
  run:
    - pbkdf2
    - python >=3.6

test:
  imports:
    - mnemonic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trezor/python-mnemonic
  summary: Implementation of Bitcoin BIP-0039
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
